### ISSUE TITLE
GT文件中的疑问

### ISSUE THREAD

**Issue by zigfried-bit** [PengYu-Team/S3E#10]
1. 请问GT文件第4列的数据的含义是什么？是和高度有关的量吗？
2. RTK的数据怎么转到imu坐标系下？RTK可以认为和IMU不存在位姿关系吗？

**Comment by xiaobrnbrn** [comment]
同问, 请问GT文件中的高程或海拔数据精度怎样? 我在square_2序列的数据中发现第4列数据并不稳定,相邻数据存在跳边的问题
