### ISSUE TITLE
Link to Dataset is Inaccessible 

### ISSUE THREAD

**Issue by IbrahimElHadka** [PengYu-Team/S3E#18]
I have been trying for more than a week to access the link to the dataset but the website is down. Can you please see what the problem is.
Thanks!

**Comment by DapengFeng** [comment]
We appreciate your interest in our research. We are currently in the process of integrating UWB data into S3E, and anticipate the release of the new dataset in the near future.

**Comment by DapengFeng** [comment]
The old data is available for download at https://pan.baidu.com/s/18zzxXACyd3W3OkbSg2vLrA?pwd=ivnm.
