### ISSUE TITLE
GT of Laboratory 1 to 4 dataset

### ISSUE THREAD

**Issue by zzwu29** [PengYu-Team/S3E#4]
Thanks for your great work!
But I cannot find the laboratory 1-4 datasets groundtruth.
Could you help me?

**Comment by DapengFeng** [comment]
The GT of Laboratory 1 to 4 are found in the file `indoor vicon.xls`
![GT of indoor environments](https://user-images.githubusercontent.com/18318646/230758607-c49a83a1-6c44-477a-b7fa-38bdccdd57a8.png)

For example, we record the start and end points of each robot in the VICON room for the Laboratory sequences, [T R] represents the translation and rotation in the VICON coordinate system. 
![example](https://user-images.githubusercontent.com/18318646/230758685-6b95430c-2b85-42a6-87f8-04adfc8671d9.png)

**Comment by zzwu29** [comment]
Thanks for your kind reply!

That means, in s3e indoor datasets, I can evaluate my algorithm results only on start and end points. While in s3e outdoor datasets, all trajectory truth can be given by RTK fix solution.
