### ISSUE TITLE
报错：点云是非稠密点云

### ISSUE THREAD

**Issue by ustccxy** [PengYu-Team/S3E#5]
使用KITTI08数据集验证DisCo-SLAM时一切正常。使用S3E_College.bag 验证DisCo-SLAM报错，非稠密点云。
您的论文中提到了在s3e数据集上验证过DisCo-SLAM，我猜测可能是我的配置文件有错误。所以想请问，是否可以提供一份你们在测试时使用的config文件。

**Comment by Cc19245** [comment]
> 使用KITTI08数据集验证DisCo-SLAM时一切正常。使用S3E_College.bag 验证DisCo-SLAM报错，非稠密点云。 您的论文中提到了在s3e数据集上验证过DisCo-SLAM，我猜测可能是我的配置文件有错误。所以想请问，是否可以提供一份你们在测试时使用的config文件。

请问这个问题你解决了吗？
