### ISSUE TITLE
How do we obtain and evaluate the ground-truth of a combination of multiple robot

### ISSUE THREAD

**Issue by NatureLan-sudo** [PengYu-Team/S3E#7]
Hello,   @DapengFeng , thank you very much for your excellent work!
As the question, I found that what we have is the groundtruth of each three robots. I found in your paper, you plot  great graphs and completed the merging of the trajectories and groundtruth of the three robots. How can I do to get such a plot, and did you get your plot by EVO at the end?
![image](https://user-images.githubusercontent.com/73154000/236828892-01e03535-047f-432f-9adc-74a7589617f7.png)

**Comment by zhongshp** [comment]
The optimized trajectories are aligned with the prior factor owner robot in the back end of DCL-SLAM. We use evo tool to align the prior factor owner robot with the ground truth to obtain its alignment, and the trajectories of all robots are transformed using the same single alignment. Finally, the trajectories of this figure are plot with matplotlib (using evo is also okay).
