### ISSUE TITLE
数据集下载慢

### ISSUE THREAD

**Issue by diamonazreal** [PengYu-Team/S3E#8]
很感谢您和您的团队制作了这样一个数据集。但是我在下载的过程中发现下载的速度很慢，完成下载过程需要花费很长时间， 请问有其他的途径可以获取数据集吗？或者有没有其他更加迅速的下载方式。期待您的回复，谢谢！

**Comment by 512938445** [comment]
蹲一个

**Comment by DapengFeng** [comment]
[BaiduYun](https://pan.baidu.com/s/18zzxXACyd3W3OkbSg2vLrA?pwd=ivnm) is available.
