### ISSUE TITLE
ROS下用ORB_SLAM3运行数据集，报错“R is not orthogonal:”

### ISSUE THREAD

**Issue by yyanzzw** [PengYu-Team/S3E#9]
您好，我在运行命令：
_rosrun ORB_SLAM3 Stereo_Inertial Vocabulary/ORBvoc.txt Examples/Stereo-Inertial/S3E.yaml false
_
的时候遇到的报错如下：

> `ORB-SLAM3 Copyright (C) 2017-2020 Carlos Campos, Richard Elvira, Juan J. Gómez, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
> ORB-SLAM2 Copyright (C) 2014-2016 Raúl Mur-Artal, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
> This program comes with ABSOLUTELY NO WARRANTY;
> This is free software, and you are welcome to redistribute it
> under certain conditions. See LICENSE.txt.
> 
> Input sensor was set to: Stereo-Inertial
> 
> Loading ORB Vocabulary. This could take a while...
> Vocabulary loaded!
> 
> Initialization of Atlas from scratch 
> Creation of new map with id: 0
> Creation of new map with last KF id: 0
> Seq. Name: 
> 
> Camera Parameters: 
> - Camera: Pinhole
> - Image scale: 1
> - fx: 1176.27
> - fy: 1176.43
> - cx: 604.755
> - cy: 518.745
> - k1: -0.050612
> - k2: 0.0979476
> - p1: -0.000419283
> - p2: -0.00025674
> - fps: 10
> - color order: RGB (ignored if grayscale)
> 
> Depth Threshold (Close/Far Points): 14.4
> 
> ORB Extractor Parameters: 
> - Number of Features: 2200
> - Scale Levels: 8
> - Scale Factor: 1.2
> - Initial Fast Threshold: 20
> - Minimum Fast Threshold: 7
> 
> Left camera to Imu Transform (Tbc): 
> [0.00464162, -0.00460674, 0.99997862, 0.12607916;
>  -0.99998633, 0.00238464, 0.00465265, 0.15840427;
>  -0.00240602, -0.99998655, -0.00459561, 0.03420431;
>  0, 0, 0, 1]
> Sophus ensure failed in function 'Sophus::SO3<Scalar_, Options>::SO3(const Transformation&) [with Scalar_ = float; int Options = 0; Sophus::SO3<Scalar_, Options>::Transformation = Eigen::Matrix<float, 3, 3>]', file '/home/bit202/anaconda3/envs/ORB_SLAM3/ORB_SLAM3/Thirdparty/Sophus/sophus/so3.hpp', line 471.
> R is not orthogonal:
>          inf 2.85271e+07  2.9486e+33
> 2.85271e+07      3.5156     4.90912
>  2.9486e+33     4.90912  8.3572e+31
> 已放弃 (核心已转储)
> `

我是按照carol.yaml的内容写了一个对应的S3E.yaml，具体内容如下：

> `%YAML:1.0
> 
> Camera.type: "PinHole"
> 
> // Camera calibration and distortion parameters (OpenCV) (equal for both cameras after stereo rectification)
> Camera.fx: 1176.269294800212
> Camera.fy: 1176.433529657170
> Camera.cx: 604.755275885255
> Camera.cy: 518.745152044285
> 
> Camera.k1: -0.050611950529281
> Camera.k2: 0.097947651917225
> Camera.p1: -0.000419283069591
> Camera.p2: -0.000256740077382
> 
> Camera.width: 1224
> Camera.height: 1024
> 
> // Camera frames per second
> Camera.fps: 10.0
> 
> // stereo baseline times fx 基线和fx的乘积
> Camera.bf: 423.4569461280763
> 
>// Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
> Camera.RGB: 1
> 
> // Close/Far threshold. Baseline times.
> ThDepth: 40.0 # 35
> 
> // Transformation from camera 0 to body-frame (imu)
> Tbc: !!opencv-matrix
>    rows: 4
>    cols: 4
>    dt: d
>    data: [0.00464162, -0.00460674,  0.99997862,  0.12607916,
>          -0.99998633,  0.00238464,  0.00465265,  0.15840427,
>          -0.00240602, -0.99998655, -0.00459561,  0.03420431,
>           0.0,         0.0,         0.0,         1.0]
> 
> // IMU noise
> IMU.NoiseGyro: 1.0216647894856925e-02
> IMU.NoiseAcc: 1.1692699862662088e-02
> IMU.GyroWalk: 8.4514305618965801e-05 
> IMU.AccWalk: 2.0413058951725431e-04
> IMU.Frequency: 100
> 
> // Stereo Rectification. Only if you need to pre-rectify the images.
> // Camera.fx, .fy, etc must be the same as in LEFT.P
> LEFT.height: 1024
> LEFT.width: 1224
> LEFT.D: !!opencv-matrix
>    rows: 1
>    cols: 5
>    dt: d
>    data: [-0.050611950529281,0.097947651917225, -0.000419283069591, -0.000256740077382, 0.0]
> LEFT.K: !!opencv-matrix
>    rows: 3
>    cols: 3
>    dt: d
>    data: [1176.269294800212,    0.0,            604.755275885255, 
>              0.0,            1176.433529657170, 518.745152044285, 
>              0.0,               0.0,              1.0]
> LEFT.R:  !!opencv-matrix
>    rows: 3
>    cols: 3
>    dt: d
>    data: [1.0, 0.0, 0.0,
>           0.0, 1.0, 0.0,
>           0.0, 0.0, 1.0]
> LEFT.Rf:  !!opencv-matrix
>    rows: 3
>    cols: 3
>    dt: d
>    data: [1.0, 0.0, 0.0, 
>           0.0, 1.0, 0.0, 
>           0.0, 0.0, 1.0]
> LEFT.P:  !!opencv-matrix
>    rows: 3
>    cols: 4
>    dt: d
>    data: [1176.269294800212,    0.0,            604.755275885255, 0.0,  
>              0.0,            1176.433529657170, 518.745152044285, 0.0,  
>              0.0,               0.0,              1.0,            0.0]
> 
> RIGHT.height: 1024
> RIGHT.width: 1224
> RIGHT.D: !!opencv-matrix
>    rows: 1
>    cols: 5
>    dt: d
>    data: [-0.050529645625590,0.100118794704043, 0.000151706619184,  0.000159873014222, 0.0]
> RIGHT.K: !!opencv-matrix
>    rows: 3
>    cols: 3
>    dt: d
>    data: [1175.693639535029,    0.0,            623.245979164071, 
>              0.0,            1175.840447155871, 509.547575123268, 
>              0.0,               0.0,              1.0]
> RIGHT.R:  !!opencv-matrix
>    rows: 3
>    cols: 3
>    dt: d
>    data: [0.999989460071177,  -0.003980443093461,  -0.002288191280272,
>           0.003974940022537,   0.999989208997031,  -0.002404525173381,
>           0.002297737664012,   0.002395404406757,   0.999994491204504]
> RIGHT.P:  !!opencv-matrix
>    rows: 3
>    cols: 4
>    dt: d
>    data: [1175.693639535029,    0.0,            623.245979164071, -361.0218672707261, 
>              0.0,            1175.840447155871, 509.547575123268,   -1.0402438315106, 
>              0.0,               0.0,              1.0,               4.6677007688895]
> 
> // ORB Parameters
> // ORB Extractor: Number of features per image
> ORBextractor.nFeatures: 2200
> 
> // ORB Extractor: Scale factor between levels in the scale pyramid
> ORBextractor.scaleFactor: 1.2
> 
>// ORB Extractor: Number of levels in the scale pyramid
> ORBextractor.nLevels: 8
> 
> // ORB Extractor: Fast threshold
> // Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
> // Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
> // You can lower these values if your images have low contrast
> ORBextractor.iniThFAST: 20
> ORBextractor.minThFAST: 7
> 
> // Viewer Parameters
> Viewer.KeyFrameSize: 0.05
> Viewer.KeyFrameLineWidth: 1
> Viewer.GraphLineWidth: 0.9
> Viewer.PointSize:2
> Viewer.CameraSize: 0.08
> Viewer.CameraLineWidth: 3
> Viewer.ViewpointX: 0
> Viewer.ViewpointY: -0.7
> Viewer.ViewpointZ: -1.8
> Viewer.ViewpointF: 500
> `

请问是标定参数需要进行什么修改吗？您能否提供使用orbslam3运行时使用的yaml文件吗，或者是其他哪一部份程序需要修改呢？非常期待您的回答！

**Comment by DapengFeng** [comment]
这是我们跑的配置文件[orb_slam3.zip](https://github.com/PengYu-Team/S3E/files/11706511/orb_slam3.zip)，希望能帮到你。

**Comment by yyanzzw** [comment]
> 这是我们跑的配置文件[orb_slam3.zip](https://github.com/PengYu-Team/S3E/files/11706511/orb_slam3.zip)，希望能帮到你。从直观上判断，应该是数据类型的问题。
> 
> 

非常感谢您的回复，经过替换yaml文件以后报错解决了，我已经可以成功运行数据集了。
